import re

from services.proposed_tool_service import add_proposed_tool


def _sanitize_tool_name(name: str) -> str:
    value = (name or "").strip().lower()
    value = value.replace(" ", "_").replace("-", "_")
    value = re.sub(r"[^a-z0-9_]", "", value)
    value = re.sub(r"_+", "_", value).strip("_")

    if not value:
        raise ValueError("Invalid tool name")

    return value


def _default_stub_code(name: str, description: str) -> str:
    tool_func = f"get_{name}"

    return f'''TOOL_SPEC = {{
    "name": "{tool_func}",
    "description": "{description}",
    "parameters": {{
        "type": "object",
        "properties": {{}},
        "required": [],
        "additionalProperties": False
    }},
    "safety": "read_only"
}}


def run(args):
    return {{
        "ok": True,
        "tool_name": "{tool_func}",
        "answer": "Proposed tool stub for {name} is not installed yet.",
        "data": {{
            "stage": "proposed",
            "name": "{name}"
        }}
    }}
'''
def generate_proposed_tool_file(name: str, description: str, code: str | None = None) -> dict:
    clean_name = _sanitize_tool_name(name)
    filename = f"{clean_name}.py"

    final_code = (code or "").strip()
    if not final_code:
        final_code = _default_stub_code(clean_name, description)

    proposal = add_proposed_tool(
        name=clean_name,
        description=description,
        filename=filename,
        code=final_code,
        requested_by="ai",
        notes="generated by ai_tool_generator",
    )

    return proposal
